name: Install deps and caching
description: Install deps and caching
inputs:
  bun-version:
    description: bun version
    required: false
    default: 1.2.18
runs:
  using: composite
  steps:
    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.BUN_VERSION }}
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
    - name: Install Dependencies
      run: bun i
